/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define AHB1_BASE_ADDR 0x30UL

#define GPIOD_BASE_ADDR 		0x40020C00UL	// Address for setting GPIO D.
#define ODR_OFFSET				0x14UL			// Offset of ODR address from GPIOD_BASE_ADDR
#define MODER_OFFSET			0x0UL			// Offset of MODER address from GPIOD_BASE_ADDR
#define RCC_AHB1ENR_ADDR 		0x40023830UL	// Address for AHB1 Bus settings.

int main(void)
{

	// Enable clock for IO port D through AHB1 bus.
	uint32_t *AHB1_ptr = (uint32_t*) RCC_AHB1ENR_ADDR;
	*AHB1_ptr |= 0b1000;

	// Set all pins to push-pull.
	uint32_t *moder_ptr = (uint32_t*) (GPIOD_BASE_ADDR + MODER_OFFSET);
	*moder_ptr |= (0b01010101) << 24;

	// Set bits in ODR (Output address register).
	uint32_t *odr_ptr = (uint32_t*) (GPIOD_BASE_ADDR + ODR_OFFSET);
	*odr_ptr |= 0b1 << 12;	// Turn on green LED.
	*odr_ptr |= 0b1 << 13;	// Turn on orange LED.
	*odr_ptr |= 0b1 << 14;	// Turn on red LED.
	*odr_ptr |= 0b1 << 15;	// Turn on blue LED.

    /* Loop forever */
	for(;;);
}
